### PR TITLE
refactor: webpack plugin

### PR DESCRIPTION
**Pull request by taishinaritomi**

### CODE REVIEW

**Comment by taishinaritomi** [comment]
:snapshot_release

**Comment by taishinaritomi** [comment]
:snapshot_release

**Comment by TaishiNaritomiAPG** [comment]
:snapshot_release

**Comment by taishinaritomi** [comment]
:snapshot_release

**Comment by taishinaritomi** [comment]
:snapshot_release

**Comment by taishinaritomi** [comment]
:snapshot_release

**Comment by taishinaritomi** [comment]
:snapshot_release

**Comment by taishinaritomi** [comment]
:snapshot_release

**Comment by taishinaritomi** [comment]
:snapshot_release

**Comment by taishinaritomi** [comment]
:snapshot_release

**Pull request merged**
